<?php
                
/**
 * @author		Leonardo Perez Justiniano
 * @copyright 	2018
 * @version     1.0
 */

require_once "data/db.inc";
require_once "data/Compra.inc";

                     
class RN_Compra extends DataBase
{
    function __construct()
    {
        $this->Open();
    }
    function Save($_osCompra)
    {
        $sql = "INSERT INTO compra values(
            ". $_osCompra->idCompra->GetValue().",
            '". $_osCompra->fechayHoraIngreso->GetValue()."',
            '". $_osCompra->fechaCompra->GetValue() ."',
            ". $_osCompra->idProveedor->GetValue().",
            ". $_osCompra->idEmpleado->GetValue().",
            ". $_osCompra->MontoTotal->GetValue().",
            ". $_osCompra->idAlmacenIngreso->GetValue().",
            ". $_osCompra->nroFactura->GetValue()."
        )";

        $res = $this->Execute($sql);

        $id   = $this->GetLastIdAutoGenerated();
        
        return $id;
    }
}
?>