<?php
                
/**
 * @author		Leonardo Perez Justiniano
 * @company 	Blaufu�
 * @copyright 	2018
 * @version     1.0
 */

require_once "data/db.inc";
require_once "data/Modulo.inc";
                     
class RN_Modulo extends DataBase
{
    function __construct()
    {
        $this->Open();
    }
    
    /** 
     * @abstract Funci�n para obtener la lista de modulo(s) 
     * @return Lista de Structure_Modulo
     */
    function GetList()
    {
        $sql = "Select * from modulo where estado = 'Activo'";
        $res = $this->Execute($sql);
        
        $list = array();
        if ($this->ContainsData($res)){
            $data = $this->DataListStructure($res);
            foreach($data as $item)
            {
                $osModulo = new Structure_Modulo;

 				$osModulo->idModulo->SetValue($item["idModulo"]);
 				$osModulo->hash->SetValue($item["hash"]);
 				$osModulo->nombre->SetValue($item["nombre"]);
 				$osModulo->estado->SetValue($item["estado"]);

 				$list[] = $osModulo;                
            }            
        }
        
        return $list;
    }
    
    /** 
     * @abstract Funci�n para obtener los Datos de modulo(s)
     * @param string hash
     * @return Structure_Modulo
     */
    function GetData($_hash)
    {
        $sql = "Select * from modulo where hash = '". $_hash . "'";
        $res = $this->Execute($sql);
        
        $osModulo = new Structure_Modulo;
        
        if ($this->ContainsData($res)){
            $data = $this->DataListStructure($res);            
            
            foreach($data as $item)
            {
 				$osModulo->idModulo->SetValue($item["idModulo"]);
 				$osModulo->hash->SetValue($item["hash"]);
 				$osModulo->nombre->SetValue($item["nombre"]);
 				$osModulo->estado->SetValue($item["estado"]);
            }            
        }
        
        return $osModulo;
    }
    
    /** 
     * @abstract Funci�n para guardar modulo
     * @param Structure_Modulo osModulo
     * @return bool
     */
    function Save($_osModulo)
    {
        $sql = "Insert into modulo values (
				" . $_osModulo->idModulo->GetValue() . ",
				'" . $_osModulo->hash->GetValue() . "',
				'" . $_osModulo->nombre->GetValue() . "',
				'" . $_osModulo->estado->GetValue() . "')";

        $res = $this->Execute($sql);

		$id   = $this->GetLastIdAutoGenerated();
		$hash = sha1($id);
		$sql2 = "Update modulo set hash = '". $hash ."' where idModulo = " . $id;
		$res2 = $this->Execute($sql2);
        
        $r = ($res and $res2) ? true : false;
		return $r;
    }
    
    /** 
     * @abstract Funci�n para actualizar modulo
     * @param Structure_Modulo osModulo
     * @return bool
     */
    function Update($_osModulo)
    {
        $sql = "Update modulo set 
					nombre = '" . $_osModulo->nombre->GetValue() . "',
					estado = '" . $_osModulo->estado->GetValue() . "'
				where hash = '" . $_osModulo->hash->GetValue() . "'";
        $res = $this->Execute($sql);
        
        return $res;
    }
    
    /** 
     * @abstract Funci�n para eliminar modulo
     * @param string hash
     * @return bool
     */
    function Delete($_hash)
    {
        $sql = "Update modulo set estado = 'Inactivo' where hash = '" . $_hash . "'";
        $res = $this->Execute($sql);
        
        return $res;
    }
}
                
?>