<?php
                
/**
 * @author		Leonardo Perez Justiniano
 * @copyright 	2018
 * @version     1.0
 */

require_once "data/db.inc";
require_once "data/Pedido.inc";
                     
class RN_Pedido extends DataBase
{
    function __construct()
    {
        $this->Open();
    }
    function SavePedido($_osPedido)
    {
        $sql = "Insert into pedido values (
				" . $_osPedido->idPedido->GetValue() . ",
				'" . $_osPedido->TotalPedido->GetValue() . "',
				'" . $_osPedido->estado->GetValue() . "',
				'" . $_osPedido->idtipoMovimiento->GetValue() . "',
				'" . $_osPedido->realizado_por->GetValue() . "',
				'" . $_osPedido->idCliente->GetValue() . "')";

        $res = $this->Execute($sql);

		$id   = $this->GetLastIdAutoGenerated();
		// $hash = sha1($id);
		// $sql2 = "Update objeto set hash = '". $hash ."' where idObjeto = " . $id;
		// $res2 = $this->Execute($sql2);
        // $r = ($res and $res2) ? true : false;
        // return $r;
        return $id;
    }
    function UpdatePedido($_osPedido2)
    {
        $sql = "Update pedido set 
        TotalPedido =" . $_osPedido2->TotalPedido->GetValue() . "
        where idPedido =" . $_osPedido2->idPedido->GetValue() . "";
        $res = $this->Execute($sql);
        return $res;

    }
}
                
?>