<?php
                
/**
 * @author		Leonardo Perez Justiniano
 * @copyright 	2018
 * @version     1.0
 */

require_once "data/db.inc";
require_once "data/ProductoAlmacen.inc";
                     
class RN_ProductoAlmacen extends DataBase
{
    function __construct()
    {
        $this->Open();
    }
    function SaveProductoAlmacen($_osProductoAlmacen)
    {
        $sql = "Insert into producto_almacen values (0,
				" . $_osProductoAlmacen->idProducto->GetValue() . ",
                " . $_osProductoAlmacen->idAlmacen->GetValue() . ",
                " . $_osProductoAlmacen->idPedido->GetValue() . ",
                NOW(),
				" . $_osProductoAlmacen->cantidad->GetValue() . ",
                '" . $_osProductoAlmacen->estado->GetValue() . "')     ";//. $_osProductoAlmacen->fechaMovimiento->GetValue() . 

        $res = $this->Execute($sql);
        if ($res == true) {
            $r = true;
        }
        else
        {
            $r = false;
        }

		// $id   = $this->GetLastIdAutoGenerated();
		// $hash = sha1($id);
		// $sql2 = "Update objeto set hash = '". $hash ."' where idObjeto = " . $id;
		// $res2 = $this->Execute($sql2);
        // $r = ($res and $res2) ? true : false;
        // return $r;
        return $r;
    }
    function VerificarStock($_)
    {
        
    }
    
    
}
                
?>