<?php
                
/**
 * @author		Leonardo Perez Justiniano
 * @copyright 	2018
 * @version     1.0
 */

require_once "data/db.inc";
require_once "data/Venta.inc";



                     
class RN_Venta extends DataBase
{
    function __construct()
    {
        $this->Open();
    }
    
    /** 
     * @abstract Funcion para obtener un cliente(s) 
     * @return Lista de Structure_ClienteGeneral
     */
    function Save($_osVenta)
    {
        $sql = "INSERT INTO `venta` values(". $_osVenta->idVenta->GetValue().",
            ". $_osVenta->idCliente->GetValue().",
            '". $_osVenta->fechayHora->GetValue() ."',
            ". $_osVenta->MontoTotal->GetValue().",
            ". $_osVenta->MontoDescuento->GetValue().",
            ". $_osVenta->idEmpleado->GetValue().",
            '". $_osVenta->estado->GetValue()."',
            ". $_osVenta->idAlmacenVenta->GetValue().")";
        $res = $this->Execute($sql);

        $id   = $this->GetLastIdAutoGenerated();
        
        return $id;
    }
}
                
?>